#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Windows 10' {
    search --fs-uuid --no-floppy --set=root EA5E-14B7
    chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
