#!/bin/bash
# Copyright (C) 2007 Michael Seiler - AccuWeather (r) RSS weather tool for conky
# Copyright (C) 2014 Nikhil Kumar - https://github.com/nikhil
# Copyright (C) 2019 Pedro Moreira - https://github.com/pponto

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?locCode\=$1\&metric\=$2 | perl -ne '

use utf8;
if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/;
my @values=split(":",$1);

if( $values[0] eq "Sunny" || $values[0] eq "Mostly Sunny" || $values[0] eq "Partly Sunny" || $values[0] eq "Intermittent Clouds" || $values[0] eq "Hazy Sunshine" || $values[0] eq "Hazy Sunshine" || $values[0] eq "Hot")
{
my $sun = "";
binmode(STDOUT, ":utf8");
print "$sun";
}
elsif( $values[0] eq "Mostly Cloudy" || $values[0] eq "Cloudy" || $values[0] eq "Dreary (Overcast)" || $values[0] eq "Fog")
{
my $cloud = "";
binmode(STDOUT, ":utf8");
print "$cloud";
}
elsif( $values[0] eq "Showers" || $values[0] eq "Mostly Cloudy w/ Showers" || $values[0] eq "Partly Sunny w/ Showers" || $values[0] eq "T-Storms"|| $values[0] eq "Mostly Cloudy w/ T-Storms"|| $values[0] eq "Partly Sunny w/ T-Storms" || $values[0] eq "Rain" || $values[0] eq "Mostly Cloudy W/ Showers" || $values[0] eq "Partly Cloudy W/ Showers")
{
my $rain = "";
binmode(STDOUT, ":utf8");
print "$rain";
}
elsif( $values[0] eq "Windy")
{
my $wind = "";
binmode(STDOUT, ":utf8");
print "$wind";
}
elsif( $values[0] eq "Thunderstorms")
{
my $thunder = "";
binmode(STDOUT, ":utf8");
print "$thunder";
} 
elsif( $values[0] eq "Flurries" || $values[0] eq "Mostly Cloudy w/ Flurries" || $values[0] eq "Partly Sunny w/ Flurries"|| $values[0] eq "Snow"|| $values[0] eq "Mostly Cloudy w/ Snow"|| $values[0] eq "Ice"|| $values[0] eq "Sleet"|| $values[0] eq "Freezing Rain"|| $values[0] eq "Rain and Snow"|| $values[0] eq "Cold")
{
my $snow = "";
binmode(STDOUT, ":utf8");
print "$snow";
}
elsif($values[0] eq "Clear" || $values[0] eq "Mostly Clear" || $values[0] eq "Partly Cloudy"|| $values[0] eq "Intermittent Clouds"|| $values[0] eq "Hazy Moonlight"|| $values[0] eq "Mostly Cloudy"|| $values[0] eq "Partly Cloudy w/ Showers"|| $values[0] eq "Mostly Cloudy w/ Showers"|| $values[0] eq "Partly Cloudy w/ T-Storms"|| $values[0] eq "Mostly Cloudy w/ Flurries" || $values[0] eq "Mostly Cloudy w/ Snow")
{
my $night = "";
binmode(STDOUT, ":utf8");
print "$night";
}
else
{
my $undef = $values[0];
binmode(STDOUT, ":utf8");
print "$undef";
}

my $regex = qr/(\d*)(C|F)/p;
if ( $values[1] =~ /$regex/g ) {
  print " $1°$2";
} else {
  print " $values[1]";
}

}
'
