#!/bin/sh

case $1 in
up)
    amixer -q -D pulse sset Master 5%+ && pkill -RTMIN+10 i3blocks
    notify-send " `amixer get -D pulse Master | grep -m 1 -o '[0-1]\?[0-9]\?[0-9]%'`"
    ;;
down)
    amixer -q -D pulse sset Master 5%- && pkill -RTMIN+10 i3blocks
    notify-send " `amixer get -D pulse Master | grep -m 1 -o '[0-1]\?[0-9]\?[0-9]%'`"
    ;;
*)
    amixer -q -D pulse sset Master toggle && pkill -RTMIN+10 i3blocks
    notify-send " `amixer get -D pulse Master | grep -m 1 -ow 'on\|off'`"
    ;;
esac
